// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace triatloncs
{
	public partial class LoginViewController : NSViewController
	{
		private TriatlonService _service = DependencyProvider.Shared.GetSharedService();

		public LoginViewController (IntPtr handle) : base (handle)
		{
		}

		partial void LogInButtonClicked(Foundation.NSObject sender)
        {
			if (_service.LogInReferee(EmailTextField.StringValue, PasswordTextField.StringValue))
			{
				var storyboard = NSStoryboard.FromName("Main", null);
				var controller = storyboard.InstantiateControllerWithIdentifier("HomeWindow") as NSWindowController;
				View.Window.OrderOut(Self);
				controller.ShowWindow(this);
			}
			else
            {
				var alert = new NSAlert()
				{
					AlertStyle = NSAlertStyle.Informational,
					InformativeText = "Combinatia email - parola nu este asociata niciunui cont de arbitru.",
					MessageText = "Credentiale gresite"
				};
				alert.RunModal();
            }
        }
	}
}
